optim_cfg:
  weight_decay: 0.000
  optimizer: 'adam'
  lr: 0.0002
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
  grad_clip: 1.0

epochs: 100
ema_rate: 0.9999
use_ema: True
batch_size: 2048
num_workers: 6
save_path: ./save_ckpt